[alembic]
# path to migration scripts
script_location = alembic

# database URL
sqlalchemy.url = postgresql+psycopg://postgres:Bookify%231234@34.55.176.77:5432/Rewards

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# installed by adding `alembic[tz]` to the pip requirements
# warning: this timezone is used when generating the filename, and
# must match the timezone used when generating the date
timezone = UTC

# max length of characters to apply to the
# migration file template
# (only applies to the default file_template)
# truncate_slug_length = 40

# set to 'true' to run the environment file as a standalone script,
# that is, without the alembic import at the top
# run_environment_as_main = false

# revision environment configuration
[alembic:revision_environment]
# set to 'true' to run the environment file as a standalone script,
# that is, without the alembic import at the top
# run_environment_as_main = false

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S